version: '3.3'

services:
    angular:
        build: angular-frontend
        ports:    
            - "4200:4200"
        volumes:
            - ./angular-frontend:/app:consistent

    express:
        build: node-express-server
        ports:
            - "3000:3000"
        volumes:
            - ./node-express-server:/usr/src/app:consistent
        links:
            - database

    database:
        image: mongo
        ports:
            - "27017:27017"